/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Zach
 */
public class InactiveStorePanel extends StorePanel {

    Store store = new Store();
    Player player = new Player("Current Player");
    Card card;
    /**
     * Creates new form StorePanelPanel
     */
    public InactiveStorePanel(View view) {
        GameManager gm = view.getGameManager();
        player = gm.getActivePlayer();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        smithyPanel = new javax.swing.JPanel();
        buySmithyButton = new javax.swing.JButton();
        smithyLabel = new javax.swing.JLabel();
        smithyImageLabel = new javax.swing.JLabel();
        MilitiaPanel = new javax.swing.JPanel();
        buyMilitiaButton = new javax.swing.JButton();
        militiaLabel = new javax.swing.JLabel();
        militiaImageLabel = new javax.swing.JLabel();
        remodelPanel = new javax.swing.JPanel();
        buyRemodelButton = new javax.swing.JButton();
        remodelLabel = new javax.swing.JLabel();
        remodelImageIcon = new javax.swing.JLabel();
        marketPanel = new javax.swing.JPanel();
        buyMarketButton = new javax.swing.JButton();
        marketLabel = new javax.swing.JLabel();
        marketsImageLabel = new javax.swing.JLabel();
        minePanel = new javax.swing.JPanel();
        buyMineButton = new javax.swing.JButton();
        mineLabel = new javax.swing.JLabel();
        mineImageLabel = new javax.swing.JLabel();
        moatPanel = new javax.swing.JPanel();
        buyMoatButton = new javax.swing.JButton();
        moatLabel = new javax.swing.JLabel();
        moatImageLabel = new javax.swing.JLabel();
        cellarPanel = new javax.swing.JPanel();
        buyCellarButton = new javax.swing.JButton();
        cellarLabel = new javax.swing.JLabel();
        cellarImageLabel = new javax.swing.JLabel();
        villagePanel = new javax.swing.JPanel();
        buyVillageButton = new javax.swing.JButton();
        villageLabel = new javax.swing.JLabel();
        villageImageLabel = new javax.swing.JLabel();
        workshopPanel = new javax.swing.JPanel();
        buyWorkshopButton = new javax.swing.JButton();
        workshopLabel = new javax.swing.JLabel();
        workshopImageLabel = new javax.swing.JLabel();
        woodcutterPanel = new javax.swing.JPanel();
        buyWoodcutterButton = new javax.swing.JButton();
        woodcutterLabel = new javax.swing.JLabel();
        woodcutterImageLabel = new javax.swing.JLabel();
        copperPanel = new javax.swing.JPanel();
        buyCopperButton = new javax.swing.JButton();
        copperImageLabel = new javax.swing.JLabel();
        silverPanel = new javax.swing.JPanel();
        buySilverButton = new javax.swing.JButton();
        silverImageLabel = new javax.swing.JLabel();
        goldPanel = new javax.swing.JPanel();
        buyGoldButton = new javax.swing.JButton();
        goldImageLabel = new javax.swing.JLabel();
        provincePanel = new javax.swing.JPanel();
        buyProvinceButton = new javax.swing.JButton();
        provinceLabel = new javax.swing.JLabel();
        provinceImageLabel = new javax.swing.JLabel();
        duchyPanel = new javax.swing.JPanel();
        buyDuchyButton = new javax.swing.JButton();
        duchyLabel = new javax.swing.JLabel();
        duchyImageLabel = new javax.swing.JLabel();
        estatePanel = new javax.swing.JPanel();
        buyEstateButton = new javax.swing.JButton();
        estateLabel = new javax.swing.JLabel();
        estateImageLabel = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        buySmithyButton.setText("Buy");

        smithyLabel.setText("Smithys Left: 10");

        smithyImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smithy.jpg"))); // NOI18N

        javax.swing.GroupLayout smithyPanelLayout = new javax.swing.GroupLayout(smithyPanel);
        smithyPanel.setLayout(smithyPanelLayout);
        smithyPanelLayout.setHorizontalGroup(
            smithyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(smithyPanelLayout.createSequentialGroup()
                .addGroup(smithyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(smithyPanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(smithyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(smithyImageLabel)
                            .addGroup(smithyPanelLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(smithyLabel))))
                    .addGroup(smithyPanelLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(buySmithyButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        smithyPanelLayout.setVerticalGroup(
            smithyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, smithyPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(smithyImageLabel)
                .addGap(18, 18, 18)
                .addComponent(buySmithyButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(smithyLabel)
                .addContainerGap())
        );

        buyMilitiaButton.setText("Buy");

        militiaLabel.setText("Militias Left: 10");

        militiaImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/militia.jpg"))); // NOI18N

        javax.swing.GroupLayout MilitiaPanelLayout = new javax.swing.GroupLayout(MilitiaPanel);
        MilitiaPanel.setLayout(MilitiaPanelLayout);
        MilitiaPanelLayout.setHorizontalGroup(
            MilitiaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MilitiaPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(MilitiaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(militiaLabel)
                    .addComponent(buyMilitiaButton))
                .addGap(52, 52, 52))
            .addGroup(MilitiaPanelLayout.createSequentialGroup()
                .addComponent(militiaImageLabel)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        MilitiaPanelLayout.setVerticalGroup(
            MilitiaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MilitiaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(militiaImageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(buyMilitiaButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(militiaLabel)
                .addContainerGap())
        );

        buyRemodelButton.setText("Buy");

        remodelLabel.setText("Remodels Left: 10");

        remodelImageIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/remodel.jpg"))); // NOI18N

        javax.swing.GroupLayout remodelPanelLayout = new javax.swing.GroupLayout(remodelPanel);
        remodelPanel.setLayout(remodelPanelLayout);
        remodelPanelLayout.setHorizontalGroup(
            remodelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(remodelPanelLayout.createSequentialGroup()
                .addGroup(remodelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(remodelPanelLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(buyRemodelButton))
                    .addGroup(remodelPanelLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(remodelLabel))
                    .addComponent(remodelImageIcon))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        remodelPanelLayout.setVerticalGroup(
            remodelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, remodelPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(remodelImageIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(buyRemodelButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(remodelLabel)
                .addContainerGap())
        );

        buyMarketButton.setText("Buy");

        marketLabel.setText("Markets Left: 10");

        marketsImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/market.jpg"))); // NOI18N

        javax.swing.GroupLayout marketPanelLayout = new javax.swing.GroupLayout(marketPanel);
        marketPanel.setLayout(marketPanelLayout);
        marketPanelLayout.setHorizontalGroup(
            marketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(marketPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(marketLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, marketPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buyMarketButton)
                .addGap(65, 65, 65))
            .addGroup(marketPanelLayout.createSequentialGroup()
                .addComponent(marketsImageLabel)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        marketPanelLayout.setVerticalGroup(
            marketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, marketPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(marketsImageLabel)
                .addGap(18, 18, 18)
                .addComponent(buyMarketButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(marketLabel)
                .addContainerGap())
        );

        buyMineButton.setText("Buy");

        mineLabel.setText("Mines Left: 10");

        mineImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mine.jpg"))); // NOI18N

        javax.swing.GroupLayout minePanelLayout = new javax.swing.GroupLayout(minePanel);
        minePanel.setLayout(minePanelLayout);
        minePanelLayout.setHorizontalGroup(
            minePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(minePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(minePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mineLabel)
                    .addComponent(buyMineButton))
                .addGap(54, 54, 54))
            .addGroup(minePanelLayout.createSequentialGroup()
                .addComponent(mineImageLabel)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        minePanelLayout.setVerticalGroup(
            minePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, minePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mineImageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(buyMineButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mineLabel)
                .addGap(13, 13, 13))
        );

        buyMoatButton.setText("Buy");

        moatLabel.setText("Moats Left: 10");

        moatImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moat.jpg"))); // NOI18N

        javax.swing.GroupLayout moatPanelLayout = new javax.swing.GroupLayout(moatPanel);
        moatPanel.setLayout(moatPanelLayout);
        moatPanelLayout.setHorizontalGroup(
            moatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(moatPanelLayout.createSequentialGroup()
                .addGroup(moatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(moatPanelLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(moatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(moatLabel)
                            .addComponent(buyMoatButton)))
                    .addGroup(moatPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(moatImageLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        moatPanelLayout.setVerticalGroup(
            moatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, moatPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(moatImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 234, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buyMoatButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(moatLabel)
                .addContainerGap())
        );

        buyCellarButton.setText("Buy");

        cellarLabel.setText("Cellars Left: 10");

        cellarImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cellar.jpg"))); // NOI18N

        javax.swing.GroupLayout cellarPanelLayout = new javax.swing.GroupLayout(cellarPanel);
        cellarPanel.setLayout(cellarPanelLayout);
        cellarPanelLayout.setHorizontalGroup(
            cellarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cellarPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(cellarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cellarPanelLayout.createSequentialGroup()
                        .addComponent(cellarImageLabel)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cellarPanelLayout.createSequentialGroup()
                        .addComponent(buyCellarButton)
                        .addGap(62, 62, 62))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cellarPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cellarLabel)
                .addGap(54, 54, 54))
        );
        cellarPanelLayout.setVerticalGroup(
            cellarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cellarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cellarImageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buyCellarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cellarLabel)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        buyVillageButton.setText("Buy");

        villageLabel.setText("Villages Left: 10");

        villageImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/village.jpg"))); // NOI18N

        javax.swing.GroupLayout villagePanelLayout = new javax.swing.GroupLayout(villagePanel);
        villagePanel.setLayout(villagePanelLayout);
        villagePanelLayout.setHorizontalGroup(
            villagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, villagePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(villageLabel)
                .addGap(60, 60, 60))
            .addGroup(villagePanelLayout.createSequentialGroup()
                .addGroup(villagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(villagePanelLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(buyVillageButton))
                    .addGroup(villagePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(villageImageLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        villagePanelLayout.setVerticalGroup(
            villagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, villagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(villageImageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buyVillageButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(villageLabel)
                .addContainerGap())
        );

        buyWorkshopButton.setText("Buy");

        workshopLabel.setText("Workshops Left: 10");

        workshopImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/workshop.jpg"))); // NOI18N

        javax.swing.GroupLayout workshopPanelLayout = new javax.swing.GroupLayout(workshopPanel);
        workshopPanel.setLayout(workshopPanelLayout);
        workshopPanelLayout.setHorizontalGroup(
            workshopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workshopPanelLayout.createSequentialGroup()
                .addGroup(workshopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(workshopPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(workshopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(workshopImageLabel)
                            .addGroup(workshopPanelLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(buyWorkshopButton))))
                    .addGroup(workshopPanelLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(workshopLabel)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        workshopPanelLayout.setVerticalGroup(
            workshopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, workshopPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(workshopImageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(buyWorkshopButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(workshopLabel)
                .addContainerGap())
        );

        buyWoodcutterButton.setText("Buy");

        woodcutterLabel.setText("Woodcutters Left: 10");

        woodcutterImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/woodcutter.jpg"))); // NOI18N

        javax.swing.GroupLayout woodcutterPanelLayout = new javax.swing.GroupLayout(woodcutterPanel);
        woodcutterPanel.setLayout(woodcutterPanelLayout);
        woodcutterPanelLayout.setHorizontalGroup(
            woodcutterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(woodcutterPanelLayout.createSequentialGroup()
                .addGroup(woodcutterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(woodcutterPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(woodcutterImageLabel))
                    .addGroup(woodcutterPanelLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(buyWoodcutterButton))
                    .addGroup(woodcutterPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(woodcutterLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        woodcutterPanelLayout.setVerticalGroup(
            woodcutterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, woodcutterPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(woodcutterImageLabel)
                .addGap(18, 18, 18)
                .addComponent(buyWoodcutterButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(woodcutterLabel)
                .addGap(20, 20, 20))
        );

        buyCopperButton.setText("Buy");

        copperImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/copperSmall.jpg"))); // NOI18N

        javax.swing.GroupLayout copperPanelLayout = new javax.swing.GroupLayout(copperPanel);
        copperPanel.setLayout(copperPanelLayout);
        copperPanelLayout.setHorizontalGroup(
            copperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(copperPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(copperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(copperPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(buyCopperButton))
                    .addComponent(copperImageLabel))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        copperPanelLayout.setVerticalGroup(
            copperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, copperPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(copperImageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buyCopperButton)
                .addGap(20, 20, 20))
        );

        buySilverButton.setText("Buy");

        silverImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/silverSmall.jpg"))); // NOI18N

        javax.swing.GroupLayout silverPanelLayout = new javax.swing.GroupLayout(silverPanel);
        silverPanel.setLayout(silverPanelLayout);
        silverPanelLayout.setHorizontalGroup(
            silverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(silverPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(silverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(silverImageLabel)
                    .addGroup(silverPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(buySilverButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        silverPanelLayout.setVerticalGroup(
            silverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, silverPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(silverImageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buySilverButton)
                .addGap(20, 20, 20))
        );

        goldPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        buyGoldButton.setText("Buy");

        goldImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goldSmall.jpg"))); // NOI18N

        javax.swing.GroupLayout goldPanelLayout = new javax.swing.GroupLayout(goldPanel);
        goldPanel.setLayout(goldPanelLayout);
        goldPanelLayout.setHorizontalGroup(
            goldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(goldPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(goldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(goldImageLabel)
                    .addGroup(goldPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(buyGoldButton)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        goldPanelLayout.setVerticalGroup(
            goldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, goldPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(goldImageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buyGoldButton)
                .addGap(36, 36, 36))
        );

        buyProvinceButton.setText("Buy");

        provinceLabel.setText("Provincess Left: 12");

        provinceImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/provinceSmall.jpg"))); // NOI18N

        javax.swing.GroupLayout provincePanelLayout = new javax.swing.GroupLayout(provincePanel);
        provincePanel.setLayout(provincePanelLayout);
        provincePanelLayout.setHorizontalGroup(
            provincePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(provincePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(provincePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(provincePanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(buyProvinceButton))
                    .addComponent(provinceImageLabel)
                    .addComponent(provinceLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        provincePanelLayout.setVerticalGroup(
            provincePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, provincePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(provinceImageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buyProvinceButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(provinceLabel)
                .addGap(22, 22, 22))
        );

        buyDuchyButton.setText("Buy");

        duchyLabel.setText("Duchys Left: 12");

        duchyImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duchySmall.jpg"))); // NOI18N

        javax.swing.GroupLayout duchyPanelLayout = new javax.swing.GroupLayout(duchyPanel);
        duchyPanel.setLayout(duchyPanelLayout);
        duchyPanelLayout.setHorizontalGroup(
            duchyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(duchyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(duchyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(duchyPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(buyDuchyButton))
                    .addComponent(duchyLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, duchyPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(duchyImageLabel)
                .addContainerGap())
        );
        duchyPanelLayout.setVerticalGroup(
            duchyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, duchyPanelLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(duchyImageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buyDuchyButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(duchyLabel))
        );

        buyEstateButton.setText("Buy");

        estateLabel.setText("Estates Left: 12");

        estateImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estateSmall.jpg"))); // NOI18N

        javax.swing.GroupLayout estatePanelLayout = new javax.swing.GroupLayout(estatePanel);
        estatePanel.setLayout(estatePanelLayout);
        estatePanelLayout.setHorizontalGroup(
            estatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(estatePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(estatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(estatePanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(buyEstateButton))
                    .addComponent(estateImageLabel)
                    .addComponent(estateLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        estatePanelLayout.setVerticalGroup(
            estatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, estatePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(estateImageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buyEstateButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(estateLabel)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(remodelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(smithyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(MilitiaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(marketPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(minePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(moatPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cellarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(villagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(workshopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(woodcutterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(copperPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(silverPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(goldPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(provincePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(duchyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(537, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cellarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(woodcutterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(moatPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(villagePanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(workshopPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(estatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(copperPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(minePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(marketPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(remodelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(smithyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MilitiaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(silverPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(duchyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(provincePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(goldPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MilitiaPanel;
    private javax.swing.JButton buyCellarButton;
    private javax.swing.JButton buyCopperButton;
    private javax.swing.JButton buyDuchyButton;
    private javax.swing.JButton buyEstateButton;
    private javax.swing.JButton buyGoldButton;
    private javax.swing.JButton buyMarketButton;
    private javax.swing.JButton buyMilitiaButton;
    private javax.swing.JButton buyMineButton;
    private javax.swing.JButton buyMoatButton;
    private javax.swing.JButton buyProvinceButton;
    private javax.swing.JButton buyRemodelButton;
    private javax.swing.JButton buySilverButton;
    private javax.swing.JButton buySmithyButton;
    private javax.swing.JButton buyVillageButton;
    private javax.swing.JButton buyWoodcutterButton;
    private javax.swing.JButton buyWorkshopButton;
    private javax.swing.JLabel cellarImageLabel;
    private javax.swing.JLabel cellarLabel;
    private javax.swing.JPanel cellarPanel;
    private javax.swing.JLabel copperImageLabel;
    private javax.swing.JPanel copperPanel;
    private javax.swing.JLabel duchyImageLabel;
    private javax.swing.JLabel duchyLabel;
    private javax.swing.JPanel duchyPanel;
    private javax.swing.JLabel estateImageLabel;
    private javax.swing.JLabel estateLabel;
    private javax.swing.JPanel estatePanel;
    private javax.swing.JLabel goldImageLabel;
    private javax.swing.JPanel goldPanel;
    private javax.swing.JLabel marketLabel;
    private javax.swing.JPanel marketPanel;
    private javax.swing.JLabel marketsImageLabel;
    private javax.swing.JLabel militiaImageLabel;
    private javax.swing.JLabel militiaLabel;
    private javax.swing.JLabel mineImageLabel;
    private javax.swing.JLabel mineLabel;
    private javax.swing.JPanel minePanel;
    private javax.swing.JLabel moatImageLabel;
    private javax.swing.JLabel moatLabel;
    private javax.swing.JPanel moatPanel;
    private javax.swing.JLabel provinceImageLabel;
    private javax.swing.JLabel provinceLabel;
    private javax.swing.JPanel provincePanel;
    private javax.swing.JLabel remodelImageIcon;
    private javax.swing.JLabel remodelLabel;
    private javax.swing.JPanel remodelPanel;
    private javax.swing.JLabel silverImageLabel;
    private javax.swing.JPanel silverPanel;
    private javax.swing.JLabel smithyImageLabel;
    private javax.swing.JLabel smithyLabel;
    private javax.swing.JPanel smithyPanel;
    private javax.swing.JLabel villageImageLabel;
    private javax.swing.JLabel villageLabel;
    private javax.swing.JPanel villagePanel;
    private javax.swing.JLabel woodcutterImageLabel;
    private javax.swing.JLabel woodcutterLabel;
    private javax.swing.JPanel woodcutterPanel;
    private javax.swing.JLabel workshopImageLabel;
    private javax.swing.JLabel workshopLabel;
    private javax.swing.JPanel workshopPanel;
    // End of variables declaration//GEN-END:variables

    @Override
    void update() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
