/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Zach
 */
public class MineStorePanel extends StorePanel {

    //freebieValue needs to be accessed from the ActionRemodel 
    Store store = new Store();
    Player player = new Player("Current Player");
    Card card;
    /**
     * Creates new form StorePanelPanel
     */
    public MineStorePanel(View view) {
        GameManager gm = view.getGameManager();
        player = gm.getActivePlayer();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        copperPanel = new javax.swing.JPanel();
        gainCopperButton = new javax.swing.JButton();
        copperImageLabel = new javax.swing.JLabel();
        silverPanel = new javax.swing.JPanel();
        gainSilverButton = new javax.swing.JButton();
        silverImageLabel = new javax.swing.JLabel();
        goldPanel = new javax.swing.JPanel();
        gainGoldButton = new javax.swing.JButton();
        goldImageLabel = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        gainCopperButton.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        gainCopperButton.setText("Gain for Free");
        gainCopperButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gainCopperButtonActionPerformed(evt);
            }
        });

        copperImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/copperSmall.jpg"))); // NOI18N

        javax.swing.GroupLayout copperPanelLayout = new javax.swing.GroupLayout(copperPanel);
        copperPanel.setLayout(copperPanelLayout);
        copperPanelLayout.setHorizontalGroup(
            copperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(copperPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(copperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gainCopperButton)
                    .addComponent(copperImageLabel))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        copperPanelLayout.setVerticalGroup(
            copperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, copperPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(copperImageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gainCopperButton)
                .addGap(20, 20, 20))
        );

        gainSilverButton.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        gainSilverButton.setText("Gain for Free");
        gainSilverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gainSilverButtonActionPerformed(evt);
            }
        });

        silverImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/silverSmall.jpg"))); // NOI18N

        javax.swing.GroupLayout silverPanelLayout = new javax.swing.GroupLayout(silverPanel);
        silverPanel.setLayout(silverPanelLayout);
        silverPanelLayout.setHorizontalGroup(
            silverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(silverPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(silverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(silverImageLabel)
                    .addComponent(gainSilverButton))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        silverPanelLayout.setVerticalGroup(
            silverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, silverPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(silverImageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gainSilverButton)
                .addGap(20, 20, 20))
        );

        goldPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        gainGoldButton.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        gainGoldButton.setText("Gain for Free");
        gainGoldButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gainGoldButtonActionPerformed(evt);
            }
        });

        goldImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goldSmall.jpg"))); // NOI18N

        javax.swing.GroupLayout goldPanelLayout = new javax.swing.GroupLayout(goldPanel);
        goldPanel.setLayout(goldPanelLayout);
        goldPanelLayout.setHorizontalGroup(
            goldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(goldPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(goldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(goldImageLabel)
                    .addComponent(gainGoldButton))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        goldPanelLayout.setVerticalGroup(
            goldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, goldPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(goldImageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(gainGoldButton)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(copperPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(silverPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(goldPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 1653, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 135, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(copperPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(silverPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(goldPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6))
        );
    }// </editor-fold>//GEN-END:initComponents

    

    
    private void gainSilverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gainSilverButtonActionPerformed
        card = new Silver();
        if (freebieValue == card.getCost())
        {
            player.getHand().add(card);
        }
        //We're not keeping track of the amount of treasure cards, so there is
        //no label to update to display the amount of silver cards remaining.
    }//GEN-LAST:event_gainSilverButtonActionPerformed

    private void gainGoldButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gainGoldButtonActionPerformed
        card = new Gold();
        if (freebieValue == card.getCost())
        {
            player.getHand().add(card);
        }
        //No label
    }//GEN-LAST:event_gainGoldButtonActionPerformed

    private void gainCopperButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gainCopperButtonActionPerformed
        card = new Copper();
        if (freebieValue == card.getCost())
        {
            player.getHand().add(card);
        }
        //No label
    }//GEN-LAST:event_gainCopperButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel copperImageLabel;
    private javax.swing.JPanel copperPanel;
    private javax.swing.JButton gainCopperButton;
    private javax.swing.JButton gainGoldButton;
    private javax.swing.JButton gainSilverButton;
    private javax.swing.JLabel goldImageLabel;
    private javax.swing.JPanel goldPanel;
    private javax.swing.JLabel silverImageLabel;
    private javax.swing.JPanel silverPanel;
    // End of variables declaration//GEN-END:variables

    @Override
    void update() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
