/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */

import com.sun.glass.events.WindowEvent;
import static java.lang.Integer.parseInt; 
import java.util.ArrayList;
import javax.swing.JFrame;
public class StartScreenPanel extends JFrame {

    int numberOfPlayers;
    ArrayList playerNames = new ArrayList<String>();
    /**
     * Creates new form NewJFrame
     */
    public StartScreenPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        choice1 = new java.awt.Choice();
        jPanel2 = new javax.swing.JPanel();
        DominionLabel = new javax.swing.JLabel();
        NumberPlayersLabel = new javax.swing.JLabel();
        Player1Label = new javax.swing.JLabel();
        Player1Name = new javax.swing.JTextField();
        StartGameButton = new javax.swing.JButton();
        NumberOfPlayers = new javax.swing.JComboBox();
        Player2Name = new javax.swing.JTextField();
        Player3Name = new javax.swing.JTextField();
        Player4Name = new javax.swing.JTextField();
        Player2Label = new javax.swing.JLabel();
        Player3Label = new javax.swing.JLabel();
        Player4Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 255, 255));

        DominionLabel.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        DominionLabel.setForeground(new java.awt.Color(255, 255, 0));
        DominionLabel.setText(" Dominion");
        DominionLabel.setAlignmentY(0.0F);

        NumberPlayersLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        NumberPlayersLabel.setText("Number of Players");

        Player1Label.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Player1Label.setText("Player 1 Name:");

        Player1Name.setText("Player 1");
        Player1Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Player1NameActionPerformed(evt);
            }
        });

        StartGameButton.setText("Start Game");
        StartGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartGameButtonActionPerformed(evt);
            }
        });

        NumberOfPlayers.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2", "3", "4" }));
        NumberOfPlayers.setSelectedIndex(2);
        NumberOfPlayers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumberOfPlayersActionPerformed(evt);
            }
        });

        Player2Name.setText("Player 2");

        Player3Name.setText("Player 3");

        Player4Name.setText("Player 4");

        Player2Label.setText("Player 2 Name:");

        Player3Label.setText("Player 3 Name:");

        Player4Label.setText("Player 4 Name:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(DominionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(185, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StartGameButton)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(NumberPlayersLabel)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Player2Label)
                                .addComponent(Player1Label)
                                .addComponent(Player3Label)
                                .addComponent(Player4Label)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Player3Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Player2Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Player1Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NumberOfPlayers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Player4Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(172, 172, 172))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(DominionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumberPlayersLabel)
                    .addComponent(NumberOfPlayers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Player1Label)
                    .addComponent(Player1Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Player2Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Player2Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Player3Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Player3Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Player4Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Player4Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(StartGameButton)
                .addGap(66, 66, 66))
        );

        Player1Name.getAccessibleContext().setAccessibleParent(Player1Name);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StartGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartGameButtonActionPerformed
        int numberOfPlayers = (int) NumberOfPlayers.getSelectedIndex();
        playerNames.add(Player1Name.getText());
        playerNames.add(Player2Name.getText());
        if (numberOfPlayers > 2){
            playerNames.add(Player3Name.getText());
        }
        if (numberOfPlayers > 3){
            playerNames.add(Player4Name.getText());
        }
        View view = new View(playerNames);
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_StartGameButtonActionPerformed

    private void Player1NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Player1NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Player1NameActionPerformed

    private void NumberOfPlayersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumberOfPlayersActionPerformed
        // TODO add your handling code here:
        if (NumberOfPlayers.getSelectedIndex() == 0){ // 2 players
            Player3Label.setVisible(false);
            Player3Name.setVisible(false);
            Player4Label.setVisible(false);
            Player4Name.setVisible(false);
        } else if (NumberOfPlayers.getSelectedIndex() == 1){ // 3 players
            Player3Label.setVisible(true);
            Player3Name.setVisible(true);
            Player4Label.setVisible(false);
            Player4Name.setVisible(false);
        } else if (NumberOfPlayers.getSelectedIndex() == 2){ // 4 players
            Player3Label.setVisible(true);
            Player3Name.setVisible(true);
            Player4Label.setVisible(true);
            Player4Name.setVisible(true);
        }
    }//GEN-LAST:event_NumberOfPlayersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartScreenPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartScreenPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartScreenPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartScreenPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartScreenPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DominionLabel;
    private javax.swing.JComboBox NumberOfPlayers;
    private javax.swing.JLabel NumberPlayersLabel;
    private javax.swing.JLabel Player1Label;
    private javax.swing.JTextField Player1Name;
    private javax.swing.JLabel Player2Label;
    private javax.swing.JTextField Player2Name;
    private javax.swing.JLabel Player3Label;
    private javax.swing.JTextField Player3Name;
    private javax.swing.JLabel Player4Label;
    private javax.swing.JTextField Player4Name;
    private javax.swing.JButton StartGameButton;
    private java.awt.Choice choice1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
